#!/bin/bash
# Xommander-utils
# By Tekin-Miz(WorldMoZara)
source lang/en_utf-8.lang
source lang/zh_utf-8.lang
if [ "$LD_PRELOAD" = '/data/data/com.termux/files/usr/lib/libtermux-exec.so' ]
then
    istermux=1
fi
mkdir -p $TMPDIR/xom
function main(){
    dialog --title "$title" --no-cancel --stderr --menu "$mainmenu_text" 16 55 10 1 "$mainmenu_opt1" 2 "$mainmenu_opt2" 3 "$mainmenu_opt3" 4 "$mainmenu_exit" 2>$TMPDIR/xom/mainopt
    main_opt=$(cat $TMPDIR/xom/mainopt)
    case "$main_opt" in
        1)
            tools
            ;;
        2)
            vision
            ;;
        3)
            extras
            ;;
        4)
            dialog --clear
            clear -x
            exit 0
            ;;
        *)
            ;;
    esac
    rm $TMPDIR/xom/mainopt
}
function tools(){
    dialog --title "$title" --stderr --menu "$toolmenu_text" 16 55 10 1 "$toolmenu_opt1" 2 "$toolmenu_opt2" 2>$TMPDIR/xom/toolopt
    if [ $? -ne 0 ]
    then
        rm $TMPDIR/xom/toolopt
        main
    else
        tool_opt=$(cat $TMPDIR/xom/toolopt)
        case $tool_opt in
            1)
                cp -f $(realpath $(dirname $0))/tools/.init.rc ~/
                if test -e $PREFIX/bin/bash
                then
                    echo -e "\nsource ~/.init.rc" >> ~/.bashrc
                fi
                if test -e $PREFIX/bin/zsh
                then
                    echo -e "\nsource ~/.init.rc" >> ~/.zshrc
                fi
                if test -e $PREFIX/bin/fish
                then
                    mkdir -p $PREFIX/etc/fish
                    echo -e "\nsource ~/.init.rc" >> $PREFIX/etc/fish/config.fish
                fi
                ;;
            2)
                ;;
            *)
                ;;
        esac
        rm $TMPDIR/xom/toolopt
    fi
}
function vision(){
    dialog --title "$title" --stderr --menu "$toolmenu_text" 16 55 10 1 "$visimenu_opt1" 2 "$visimenu_opt2" 3 "$visimenu_opt3" 2>$TMPDIR/xom/visiopt
    if [ $? -ne 0 ]
    then
        rm $TMPDIR/xom/visiopt
        main
    else
        visi_opt=$(cat $TMPDIR/xom/visiopt)
        case $visi_opt in
            1)
                uvimrc awesome
                ;;
            2)
                uvimrc basic
                ;;
            3)
                dialog --title "$title" --stderr --defaultno --yesno "$uvimrc_warn" 16 55
                if [ $? -eq 0 ]
                then
                    git clone https://github.com/gpakosz/.tmux.git ~/.tmux/
                    ln -s -f .tmux/.tmux.conf ~/.tmux.conf
                    cp .tmux/.tmux.conf.local ~/
                fi
                vision
                ;;
            *)
                ;;
        esac
        rm $TMPDIR/xom/visiopt
    fi
}
function extras(){
    dialog --title "$title" --stderr --menu "$extramenu_text" 16 55 10 1 "$extramenu_opt1" 2 "$extramenu_opt2" 2>$TMPDIR/xom/extraopt
    if [ $? -ne 0 ]
    then
        rm $TMPDIR/xom/extraopt
        main
    else
        extra_opt=$(cat $TMPDIR/xom/extraopt)
        case $extra_opt in
            1)
                if [ $istermux -eq 1 ]
                then
                    termux
                else
                    dialog --title "$title" --defaultno --stderr --yesno "$termux_warn" 16 55
                    if [ $? -eq 0 ]
                    then
                        termux
                    else
                        extras
                    fi
                    :
                fi
                ;;
            2)
                ;;
            *)
                ;;
        esac
        rm $TMPDIR/xom/extraopt
    fi
}
function uvimrc(){
    dialog --title "$title" --stderr --defaultno --yesno "$uvimrc_warn" 16 55
    if [ $? -eq 0 ]
    then
        case $1 in
            awesome)
                git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
                sh ~/.vim_runtime/install_awesome_vimrc.sh
                ;;
            basic)
                git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
                sh ~/.vim_runtime/install_basic_vimrc.sh
                ;;
            *)
                ;;
        esac
    fi
    vision
}
function termux(){
    dialog --title "$title" --stderr --menu "$toolmenu_text" 16 55 10 1 "$termuxmenu_opt1" 2 "$termuxmenu_opt2" 2>$TMPDIR/xom/termuxopt
    if [ $? -ne 0 ]
    then
        rm $TMPDIR/xom/termuxopt
        extras
    else
        termux_opt=$(cat $TMPDIR/xom/termuxopt)
        case $termux_opt in
            1)
                extkeys
                ;;
            2)
                ;;
            *)
                ;;
        esac
        rm $TMPDIR/xom/termuxopt
    fi
}
function extkeys(){
    dialog --title "$title" --stderr --menu "$extramenu_text" 16 55 10 1 "$extkeymenu_opt1" 2 "$extkeymenu_opt2" 2>$TMPDIR/xom/extkeyopt
    if [ $? -ne 0 ]
    then
        rm $TMPDIR/xom/extkeyopt
        termux
    else
        extkey_opt=$(cat $TMPDIR/xom/extkeyopt)
        case $extkey_opt in
            1)
                mkdir ~/.termux
                echo "\nextra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]\n" >> ~/.termux/termux.properties
                termux
                ;;
            2)
                ;;
            *)
                ;;
        esac
        rm $TMPDIR/xom/extkeyopt
    fi
}
main
