#!/bin/bash
# Xommander-utils
# By Tekin-Miz(WorldMoZara)
source lang/zh_utf-8.lang
function main(){
    dialog --title "$title" --stderr --menu "$mainmenu_text" 16 55 10 1 "$mainmenu_opt1" 2 "$mainmenu_opt2" 2>$PREFIX/tmp/mainopt
    main_opt=$(cat $PREFIX/tmp/mainopt)
    case "$main_opt" in
        1)
            tools
            ;;
        2)
            ;;
        3)
            ;;
        *)
            ;;
    esac
    rm $PREFIX/tmp/mainopt
}
function tools(){
    dialog --title "$title" --stderr --menu "$toolmenu_text" 16 55 10  1 "$toolmenu_opt1" 2 "$toolmenu_opt2" 2>$PREFIX/tmp/toolopt
    tool_opt=$(cat $PREFIX/tmp/toolopt)
    case $tool_opt in
        1)
            ;;
        2)
            ;;
        *)
            ;;
    esac
    rm $PREFIX/tmp/toolopt
}
main
